### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by btfurukawatkr** [btfurukawatkr/memo#2]
- [x] install CentOS7
- [x] install java
- [x] install maven
- [x] install tomcat
- [x] install GitBucket
- [x] install jenkins
- [x] install nexus
- [ ] SonarQube install
- [ ] create mail server
- [x] create a hook to run jenkins job when pull request is created in GitBucket
- [ ] create a jenkins job to run SonarQube
- [ ] create service for nexus
- [ ] package vagrant box
